-- 1. set schema
use schema DT_SOFTWARE_ENGINEERING_DEV.RDIM;
select * from DIM_DEALER_S3;

-- 2. Show primary key
show primary keys in DIM_CUSTOMER;
SHOW PRIMARY KEYS
    [ IN { ACCOUNT | DATABASE [ DT_SOFTWARE_ENGINEERING_DEV ] | SCHEMA [ RDIM ] | TABLE | [ TABLE ] DIM_CUSTOMER } ] ;

-- truncate table DIM_CUSTOMER;

-- 3. delete operation
delete from DIM_CUSTOMER_S3 
where DLR_CD = 1089761 AND SOURCESYSTEM = 'DT2'
AND CC_ID=113262028505511000 and UPPER_FRST_NM='TOM';

SELECT *
--DLR_CD.CC_ID,UPPER_FRST_NM
FROM DIM_CUSTOMER --_S3 
WHERE DLR_CD=1089761 AND SOURCESYSTEM= 'DT2'
    AND CC_ID=113262028505511000;
    
SELECT DLR_CD, DEALERID, SOURCESYSTEM, CC_ID, count(*)
  FROM DIM_CUSTOMER 
 WHERE DLR_CD=1089761 AND SOURCESYSTEM= 'DT2'
    AND CC_ID=113262028505511000
group by DLR_CD, DEALERID, SOURCESYSTEM, CC_ID;

-- 4. update operation
UPDATE DIM_CUSTOMER_S3
   SET UPPER_FRST_NM = 'Tao'
WHERE DLR_CD=1089761
    AND SOURCESYSTEM= 'DT2'
    AND CC_ID=113262028505511000;


UPDATE DIM_CUSTOMER_S3 
   SET UPPER_FRST_NM = 'TOM'
WHERE DLR_CD=1089761
    AND SOURCESYSTEM= 'DT2'
    AND CC_ID=113262028505511000;
    and UPPER_FRST_NM ='Tom';


UPDATE DIM_CUSTOMER_S3 
   SET UPPER_FRST_NM = 'Tom'
WHERE DLR_CD=1089761 AND SOURCESYSTEM= 'DT2'
AND CC_ID = 113262028505511000 and UPPER_FRST_NM ='BIDEN';

UPDATE DIM_CUSTOMER_S3 
SET UPPER_FRST_NM = 'SMITHONE'
WHERE DLR_CD=1089761 AND SOURCESYSTEM= 'DT2'
AND CC_ID = 113262028505511000;

-- 5. Check stream
SELECT * FROM DIM_CUSTOMER_STREAM;
SELECT DLR_CD, CC_ID, UPPER_FRST_NM, UPPER_LAST_NM, 
        METADATA$ACTION, METADATA$ISUPDATE, ETS_CREATED_TS,ETS_UPDATED_TS 
FROM DIM_CUSTOMER_STREAM;

SELECT COUNT(1) FROM DIM_CUSTOMER_STREAM;
-- SELECT COUNT(*) FROM DIM_CUSTOMER_STREAM_APPEND_ONLY;

SELECT * FROM DIM_CUSTOMER_STREAM_APPEND_ONLY;

SELECT * FROM DIM_CUSTOMER_S3;
SELECT COUNT (*) FROM DIM_CUSTOMER_S3; 
--215025

update DIM_CUSTOMER_S3; 
set op='I';


SELECT COUNT(*) FROM DIM_CUSTOMER;
-- 215025
SELECT COUNT(*) FROM DIM_CUSTOMER_STREAM 
WHERE NOT (METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = TRUE);

truncate table DIM_CUSTOMER;


MERGE INTO DT_SOFTWARE_ENGINEERING_DEV.RDIM.DIM_CUSTOMER T1 
USING (SELECT * FROM DT_SOFTWARE_ENGINEERING_DEV.RDIM.DIM_CUSTOMER_STREAM 
        WHERE NOT (METADATA$ACTION  = 'DELETE' AND METADATA$ISUPDATE = TRUE)
)t2 ON T1.DLR_CD=T2.DLR_CD and
T1.DEALERID=T2.DEALERID and
T1.SOURCESYSTEM=T2.SOURCESYSTEM and
T1.CC_ID=T2.CC_ID
 WHEN MATCHED --AND t2.isNewStatus = 1 
 AND T2.METADATA$ACTION = 'INSERT'
    AND T2.METADATA$ISUPDATE 
    THEN 
     UPDATE SET 
        T1.CUST_ID=T2.CUST_ID,
        T1.EXTRNL_CUST_ID=T2.EXTRNL_CUST_ID,
        T1.IS_BUSN_IN=T2.IS_BUSN_IN,
        T1.UPPER_BUSN_NM=T2.UPPER_BUSN_NM,
        T1.BUSN_TAX_ID_NB=T2.BUSN_TAX_ID_NB,
        T1.BUSN_TYP_CD=T2.BUSN_TYP_CD,
        T1.UPPER_FRST_NM=T2.UPPER_FRST_NM,
        T1.MIDDLE_NM=T2.MIDDLE_NM,
        T1.UPPER_LAST_NM=T2.UPPER_LAST_NM,
        T1.BIRTH_MTH_CD=T2.BIRTH_MTH_CD,
        T1.BIRTH_DD_NB=T2.BIRTH_DD_NB,
        T1.TAX_ID_LAST_FOUR_NB=T2.TAX_ID_LAST_FOUR_NB,
        T1.EMPL_CT=T2.EMPL_CT,
        T1.STATE=T2.STATE,
        T1.INCORP_ST_PROVNC_CD=T2.INCORP_ST_PROVNC_CD,
        T1.YEARS_EMPLOYED=T2.YEARS_EMPLOYED,
        T1.MONTHS_EMPLOYED=T2.MONTHS_EMPLOYED,
        T1.MORTGAGE_PAYMT_OR_RENT_AM=T2.MORTGAGE_PAYMT_OR_RENT_AM,
        T1.SALARY_ANNUAL=T2.SALARY_ANNUAL,
        T1.OTHER_INCOME=T2.OTHER_INCOME,
        T1.TOTAL_SALARY=T2.TOTAL_SALARY,
        T1.CREATED_BY_USER_CD=T2.CREATED_BY_USER_CD,
        T1.CREATED_TS=T2.CREATED_TS,
        T1.UPDTD_BY_USER_CD=T2.UPDTD_BY_USER_CD,
        T1.UPDTD_TS=T2.UPDTD_TS,
        T1.UNI_BATCH_ID=T2.UNI_BATCH_ID,
        T1.ADS_CREATED_TS=T2.ADS_CREATED_TS,
        T1.ADS_UPDATED_TS=T2.ADD_UPDATED_TS,
        T1.POSTAL_CD=T2.POSTAL_CD,
        T1.EMAIL_ADDRESS=T2.EMAIL_ADDRESS,
        T1.SOURCE_OTHER_INCOME=T2.SOURCE_OTHER_INCOME,
        T1.HOME_PHONE=T2.HOME_PHONE,
        T1.CELL_PHONE=T2.CELL_PHONE,
        T1.BIZ_PHONE=T2.BIZ_PHONE,
        T1.PEMP_PHONE=T2.PEMP_PHONE,
        T1.YEARS_AT_ADDRESS=T2.YEARS_AT_ADDRESS,
        T1.MONTHS_AT_ADDRESS=T2.MONTHS_AT_ADDRESS,
        T1.ADDRESS_LN_1=T2.ADDRESS_LN_1,
        T1.ADDRESS_LN_2=T2.ADDRESS_LN_2,
        T1.STREET_NB=T2.STREET_NB,
        T1.STREET_NM=T2.STREET_NM,
        T1.APARTMENT_NB=T2.APARTMENT_NB,
        T1.CTY_NM=T2.CTY_NM,
        T1.ST_PROVNC_CD=T2.ST_PROVNC_CD,
        T1.ETS__UPDATED_TS=CURRENT_TIMESTAMP
---WHEN MATCHED AND T2.METADATA$ACTION = 'DELETE' THEN DELETE
WHEN NOT MATCHED THEN INSERT (DLR_CD,
        DEALERID,
        SOURCESYSTEM,
        CC_ID,
        CUST_ID,
        EXTRNL_CUST_ID,
        IS_BUSN_IN,
        UPPER_BUSN_NM,
        BUSN_TAX_ID_NB,
        BUSN_TYP_CD,
        UPPER_FRST_NM,
        MIDDLE_NM,
        UPPER_LAST_NM,
        BIRTH_MTH_CD,
        BIRTH_DD_NB,
        TAX_ID_LAST_FOUR_NB,
        EMPL_CT,
        STATE,
        INCORP_ST_PROVNC_CD,
        YEARS_EMPLOYED,
        MONTHS_EMPLOYED,
        MORTGAGE_PAYMT_OR_RENT_AM,
        SALARY_ANNUAL,
        OTHER_INCOME,
        TOTAL_SALARY,
        CREATED_BY_USER_CD,
        CREATED_TS,
        UPDTD_BY_USER_CD,
        UPDTD_TS,
        UNI_BATCH_ID,
        ADS_CREATED_TS,
        ADS_UPDATED_TS,
        POSTAL_CD,
        EMAIL_ADDRESS,
        SOURCE_OTHER_INCOME,
        HOME_PHONE,
        CELL_PHONE,
        BIZ_PHONE,
        PEMP_PHONE,
        YEARS_AT_ADDRESS,
        MONTHS_AT_ADDRESS,
        ADDRESS_LN_1,
        ADDRESS_LN_2,
        STREET_NB,
        STREET_NM,
        APARTMENT_NB,
        CTY_NM,
        ST_PROVNC_CD
        ) VALUES (DLR_CD,
        DEALERID,
        SOURCESYSTEM,
        CC_ID,
        CUST_ID,
        EXTRNL_CUST_ID,
        IS_BUSN_IN,
        UPPER_BUSN_NM,
        BUSN_TAX_ID_NB,
        BUSN_TYP_CD,
        UPPER_FRST_NM,
        MIDDLE_NM,
        UPPER_LAST_NM,
        BIRTH_MTH_CD,
        BIRTH_DD_NB,
        TAX_ID_LAST_FOUR_NB,
        EMPL_CT,
        STATE,
        INCORP_ST_PROVNC_CD,
        YEARS_EMPLOYED,
        MONTHS_EMPLOYED,
        MORTGAGE_PAYMT_OR_RENT_AM,
        SALARY_ANNUAL,
        OTHER_INCOME,
        TOTAL_SALARY,
        CREATED_BY_USER_CD,
        CREATED_TS,
        UPDTD_BY_USER_CD,
        UPDTD_TS,
        UNI_BATCH_ID,
        ADS_CREATED_TS,
        ADD_UPDATED_TS,
        POSTAL_CD,
        EMAIL_ADDRESS,
        SOURCE_OTHER_INCOME,
        HOME_PHONE,
        CELL_PHONE,
        BIZ_PHONE,
        PEMP_PHONE,
        YEARS_AT_ADDRESS,
        MONTHS_AT_ADDRESS,
        ADDRESS_LN_1,
        ADDRESS_LN_2,
        STREET_NB,
        STREET_NM,
        APARTMENT_NB,
        CTY_NM,
        ST_PROVNC_CD
        );

        
USE ROLE SNOWFLAKE_DT_SOFTWARE_ENGINEERING_DEV_CREATORS; 
USE WAREHOUSE WHS_DT_SOFTWARE_ENGINEERING;

create or replace task DT_SOFTWARE_ENGINEERING_DEV.RDIM.dim_customer_task
warehouse = WHS_DT_SOFTWARE_ENGINEERING
schedule ='5 minute'
when system$stream_has_data('DT_SOFTWARE_ENGINEERING_DEV.RDIM.DIM_CUSTOMER_STREAM')
AS 
MERGE INTO DT_SOFTWARE_ENGINEERING_DEV.RDIM.DIM_CUSTOMER T1 
USING (SELECT * 
        FROM DT_SOFTWARE_ENGINEERING_DEV.RDIM.DIM_CUSTOMER_STREAM 
        WHERE NOT (METADATA$ACTION  = 'DELETE' AND METADATA$ISUPDATE = TRUE)
    )t2 ON T1.DLR_CD=T2.DLR_CD and
            T1.DEALERID=T2.DEALERID and
            T1.SOURCESYSTEM=T2.SOURCESYSTEM and
            T1.CC_ID=T2.CC_ID
 WHEN MATCHED --AND t2.isNewStatus = 1 
 AND T2.METADATA$ACTION = 'INSERT'
    AND T2.METADATA$ISUPDATE 
    THEN 
     UPDATE SET 
        T1.CUST_ID=T2.CUST_ID,
        T1.EXTRNL_CUST_ID=T2.EXTRNL_CUST_ID,
        T1.IS_BUSN_IN=T2.IS_BUSN_IN,
        T1.UPPER_BUSN_NM=T2.UPPER_BUSN_NM,
        T1.BUSN_TAX_ID_NB=T2.BUSN_TAX_ID_NB,
        T1.BUSN_TYP_CD=T2.BUSN_TYP_CD,
        T1.UPPER_FRST_NM=T2.UPPER_FRST_NM,
        T1.MIDDLE_NM=T2.MIDDLE_NM,
        T1.UPPER_LAST_NM=T2.UPPER_LAST_NM,
        T1.BIRTH_MTH_CD=T2.BIRTH_MTH_CD,
        T1.BIRTH_DD_NB=T2.BIRTH_DD_NB,
        T1.TAX_ID_LAST_FOUR_NB=T2.TAX_ID_LAST_FOUR_NB,
        T1.EMPL_CT=T2.EMPL_CT,
        T1.STATE=T2.STATE,
        T1.INCORP_ST_PROVNC_CD=T2.INCORP_ST_PROVNC_CD,
        T1.YEARS_EMPLOYED=T2.YEARS_EMPLOYED,
        T1.MONTHS_EMPLOYED=T2.MONTHS_EMPLOYED,
        T1.MORTGAGE_PAYMT_OR_RENT_AM=T2.MORTGAGE_PAYMT_OR_RENT_AM,
        T1.SALARY_ANNUAL=T2.SALARY_ANNUAL,
        T1.OTHER_INCOME=T2.OTHER_INCOME,
        T1.TOTAL_SALARY=T2.TOTAL_SALARY,
        T1.CREATED_BY_USER_CD=T2.CREATED_BY_USER_CD,
        T1.CREATED_TS=T2.CREATED_TS,
        T1.UPDTD_BY_USER_CD=T2.UPDTD_BY_USER_CD,
        T1.UPDTD_TS=T2.UPDTD_TS,
        T1.UNI_BATCH_ID=T2.UNI_BATCH_ID,
        T1.ADS_CREATED_TS=T2.ADS_CREATED_TS,
        T1.ADS_UPDATED_TS=T2.ADD_UPDATED_TS,
        T1.POSTAL_CD=T2.POSTAL_CD,
        T1.EMAIL_ADDRESS=T2.EMAIL_ADDRESS,
        T1.SOURCE_OTHER_INCOME=T2.SOURCE_OTHER_INCOME,
        T1.HOME_PHONE=T2.HOME_PHONE,
        T1.CELL_PHONE=T2.CELL_PHONE,
        T1.BIZ_PHONE=T2.BIZ_PHONE,
        T1.PEMP_PHONE=T2.PEMP_PHONE,
        T1.YEARS_AT_ADDRESS=T2.YEARS_AT_ADDRESS,
        T1.MONTHS_AT_ADDRESS=T2.MONTHS_AT_ADDRESS,
        T1.ADDRESS_LN_1=T2.ADDRESS_LN_1,
        T1.ADDRESS_LN_2=T2.ADDRESS_LN_2,
        T1.STREET_NB=T2.STREET_NB,
        T1.STREET_NM=T2.STREET_NM,
        T1.APARTMENT_NB=T2.APARTMENT_NB,
        T1.CTY_NM=T2.CTY_NM,
        T1.ST_PROVNC_CD=T2.ST_PROVNC_CD,
        T1.ETS__UPDATED_TS=CURRENT_TIMESTAMP
---WHEN MATCHED AND T2.METADATA$ACTION = 'DELETE' THEN DELETE
WHEN NOT MATCHED THEN INSERT (DLR_CD,
        DEALERID,
        SOURCESYSTEM,
        CC_ID,
        CUST_ID,
        EXTRNL_CUST_ID,
        IS_BUSN_IN,
        UPPER_BUSN_NM,
        BUSN_TAX_ID_NB,
        BUSN_TYP_CD,
        UPPER_FRST_NM,
        MIDDLE_NM,
        UPPER_LAST_NM,
        BIRTH_MTH_CD,
        BIRTH_DD_NB,
        TAX_ID_LAST_FOUR_NB,
        EMPL_CT,
        STATE,
        INCORP_ST_PROVNC_CD,
        YEARS_EMPLOYED,
        MONTHS_EMPLOYED,
        MORTGAGE_PAYMT_OR_RENT_AM,
        SALARY_ANNUAL,
        OTHER_INCOME,
        TOTAL_SALARY,
        CREATED_BY_USER_CD,
        CREATED_TS,
        UPDTD_BY_USER_CD,
        UPDTD_TS,
        UNI_BATCH_ID,
        ADS_CREATED_TS,
        ADS_UPDATED_TS,
        POSTAL_CD,
        EMAIL_ADDRESS,
        SOURCE_OTHER_INCOME,
        HOME_PHONE,
        CELL_PHONE,
        BIZ_PHONE,
        PEMP_PHONE,
        YEARS_AT_ADDRESS,
        MONTHS_AT_ADDRESS,
        ADDRESS_LN_1,
        ADDRESS_LN_2,
        STREET_NB,
        STREET_NM,
        APARTMENT_NB,
        CTY_NM,
        ST_PROVNC_CD
        ) VALUES (DLR_CD,
        DEALERID,
        SOURCESYSTEM,
        CC_ID,
        CUST_ID,
        EXTRNL_CUST_ID,
        IS_BUSN_IN,
        UPPER_BUSN_NM,
        BUSN_TAX_ID_NB,
        BUSN_TYP_CD,
        UPPER_FRST_NM,
        MIDDLE_NM,
        UPPER_LAST_NM,
        BIRTH_MTH_CD,
        BIRTH_DD_NB,
        TAX_ID_LAST_FOUR_NB,
        EMPL_CT,
        STATE,
        INCORP_ST_PROVNC_CD,
        YEARS_EMPLOYED,
        MONTHS_EMPLOYED,
        MORTGAGE_PAYMT_OR_RENT_AM,
        SALARY_ANNUAL,
        OTHER_INCOME,
        TOTAL_SALARY,
        CREATED_BY_USER_CD,
        CREATED_TS,
        UPDTD_BY_USER_CD,
        UPDTD_TS,
        UNI_BATCH_ID,
        ADS_CREATED_TS,
        ADD_UPDATED_TS,
        POSTAL_CD,
        EMAIL_ADDRESS,
        SOURCE_OTHER_INCOME,
        HOME_PHONE,
        CELL_PHONE,
        BIZ_PHONE,
        PEMP_PHONE,
        YEARS_AT_ADDRESS,
        MONTHS_AT_ADDRESS,
        ADDRESS_LN_1,
        ADDRESS_LN_2,
        STREET_NB,
        STREET_NM,
        APARTMENT_NB,
        CTY_NM,
        ST_PROVNC_CD
        );




        